#!/usr/bin/env ruby
EXE_FLAG = ARGV[0];

if (EXE_FLAG == "build")
  system("cargo remote -- build --release --no-default-features --lib")
elsif (EXE_FLAG == "test")
  system("cargo remote -- test --release --no-default-features --lib")
else
  system("cargo remote -- run --release");
end

